name: 7.0-alpine
on: [push]
jobs:
  build:
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0-alpine
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
        LC_ALL: en_AU.UTF-8
        LANG: en_AU.UTF-8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet run --no-build