name: Build
on: [push]
jobs:
  build-6.0.301-alpine3.14:
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0.301-alpine3.14
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
        LC_ALL: en_AU.UTF-8
        LANG: en_AU.UTF-8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: dotnet run

  build-6.0.301-alpine3.15:
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0.301-alpine3.15
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
        LC_ALL: en_AU.UTF-8
        LANG: en_AU.UTF-8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: dotnet run

  build-6.0.301-alpine3.16:
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0.301-alpine3.16
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
        LC_ALL: en_AU.UTF-8
        LANG: en_AU.UTF-8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: dotnet run

  build-6.0.302-alpine3.15:
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0.302-alpine3.15
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
        LC_ALL: en_AU.UTF-8
        LANG: en_AU.UTF-8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: dotnet run

  build-6.0.302-alpine3.16:
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0.302-alpine3.16
      env:
        DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
        LC_ALL: en_AU.UTF-8
        LANG: en_AU.UTF-8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: dotnet run